### ISSUE TITLE
remove mpiposix from HDF5 driver

### ISSUE THREAD

**Issue by aowen87** [visit-dav/silo-issues#40]
-----------------------REDMINE MIGRATION-----------------------
This ticket was migrated from Redmine. As such, not all 
information was able to be captured in the transition. Below is
a complete record of the original redmine ticket.

Ticket number: 2124
Status: Resolved
Project: VisIt
Tracker: Bug
Priority: Normal
Subject: remove mpiposix from HDF5 driver
Assigned to: -
Category: -
Target version: 4.10.3
Author: Mark Miller
Start: 01/26/2015
Due date: 
% Done: 0%
Estimated time: 
Created: 01/26/2015 07:47 pm
Updated: 04/03/2015 01:15 am
Likelihood: 4 - Common
Severity: 4 - Crash / Wrong Results
Found in version: 4.8
Impact: 
Expected Use: 
OS: All
Support Group: Any
Description:
 

Comments:

**Comment by markcmiller86** [comment]
Handled in rev856 on trunk
